apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: edgex-core-consul
  name: edgex-core-consul
spec:
  clusterIP: None
  selector:
    io.kompose.service: edgex-core-consul
status:
  loadBalancer: {}
