apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: edgex-core-data
  name: edgex-core-data
spec:
  clusterIP: None
  selector:
    io.kompose.service: edgex-core-data
status:
  loadBalancer: {}
