apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: edgex-export-distro
  name: edgex-export-distro
spec:
  clusterIP: None
  selector:
    io.kompose.service: edgex-export-distro
status:
  loadBalancer: {}
