apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: edgex-support-logging
  name: edgex-support-logging
spec:
  clusterIP: None
  selector:
    io.kompose.service: edgex-support-logging
status:
  loadBalancer: {}
