apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: edgex-core-metadata
  name: edgex-core-metadata
spec:
  clusterIP: None
  selector:
    io.kompose.service: edgex-core-metadata
status:
  loadBalancer: {}
