apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: edgex-mongo
  name: edgex-mongo
spec:
  clusterIP: None
  selector:
    io.kompose.service: edgex-mongo
status:
  loadBalancer: {}
