apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: edgex-device-mqtt
  name: edgex-device-mqtt
spec:
  clusterIP: None
  selector:
    io.kompose.service: edgex-device-mqtt
status:
  loadBalancer: {}
