apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: edgex-support-rulesengine
  name: edgex-support-rulesengine
spec:
  clusterIP: None
  selector:
    io.kompose.service: edgex-support-rulesengine
status:
  loadBalancer: {}
