apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: edgex-vault
  name: edgex-vault
spec:
  type: NodePort
  ports:
  - name: "8200"
    port: 8200
    targetPort: 8200
    nodePort: 30011
  selector:
    io.kompose.service: edgex-vault
status:
  loadBalancer: {}
